### ISSUE TITLE
Evaluations Error

### ISSUE THREAD

**Issue by D3STRON** [ncxlib/NeuralNetwork#37]
When I am running the code provided in the readme it gives the following error 

```
Traceback (most recent call last):
  File "C:\Users\GHOSH\OneDrive\Documents\GitHub\ncxlibtesting\temp.py", line 55, in <module>
    model.evaluate(X_test, y_test)
  File "C:\Users\GHOSH\OneDrive\Documents\GitHub\ncxlibtesting\ncvenv\lib\site-packages\ncxlib\neuralnetwork\neuralnet\nn.py", line 173, in evaluate
    negative_class = unique_targets[unique_targets < 0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by D3STRON** [comment]
Fixed in pr please take a look #38

**Comment by cwcoogan** [comment]
@D3STRON Thanks! Will take a look now.

**Comment by cwcoogan** [comment]
Merged and approved.
